### ISSUE TITLE
Int error 

### ISSUE THREAD

**Issue by nholz** [jrnewell/spotify-ripper#115]
I'll geht groß, when I try to rip to a playlist with playlist sync option (nothing more) : error_type = spotify.ErrorType(sp_error)
  File "/usr/local/lib/python2.7/dist-packages/spotify/utils.py", line 130, in __new__
    cls._values[value] = int.__new__(cls, value)
OverflowError: Python int too large to convert to C long
>From cffi callback <function scrobble_error at 0x2306230>:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/spotify/session.py", line 1114, in scrobble_error
    error_type = spotify.ErrorType(sp_error)

**Comment by jrnewell** [comment]
i will look into fixing this for Python 2, but apparently this shouldn't be an issue when using Python 3.

**Comment by nholz** [comment]
Hey, how can I tell spotify ripper to run with Python 3?

**Comment by jrnewell** [comment]
I think this should be fixed in ``2.6.0``, sorry for the delay.

**Comment by nholz** [comment]
Thanks for your effort, but it still throws this exception :(. 

Am 7. Oktober 2015 05:03:59 MESZ, schrieb James Newell <notifications@github.com>:
>I think this should be fixed in ``2.6.0``, sorry for the delay.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/jrnewell/spotify-ripper/issues/115#issuecomment-146065220

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by jrnewell** [comment]
do you have the spotify uri of track it is failing on (I assume it is a really long song) so I can test my changes?

**Comment by jrnewell** [comment]
Can you give the full argument options you are using and any config params?  Do you see this all the time or just with a specific playlist.  The more I look at this, the more it looks like it is coming from pyspotify.

**Comment by jrnewell** [comment]
Do you have lastfm scrobbling turned on for your Spotify user account?

**Comment by nholz** [comment]
Sorry for my late response: 
Here are the details: 
I see the error before loading the track of a playlist, so it's NOT a track issue. 
It does not occur all the time, but only for specific playlists. 
I reckon that the length of the playlist name is the problem.  
I do not use any config parameters, but only the default values. 
I did not turn on lastfm scrobbling.
