### ISSUE TITLE
Unicode Error

### ISSUE THREAD

**Issue by nholz** [jrnewell/spotify-ripper#98]
Hi, If I try to sync a playlist with 

spotify-ripper  --playlist-sync -f "{playlist}/{idx:3}-{artist} - {track_name}.{ext}" 

the following happens:
Spotify Ripper - v2.4.0
  Encoding output:      MP3, VBR 0
  Spotify bitrate:      320 kbps
  Unicode support:      Yes
  Format String:        {playlist}/{idx:3}-{artist} - {track_name}.{ext}
  Overwrite files:      No
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/ripper.py", line 235, in run
    self.sync.sync_playlist(self.current_playlist)
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/sync.py", line 89, in sync_playlist
    self.save_sync_library(playlist, new_lib)
  File "/usr/local/lib/python2.7/dist-packages/spotify_ripper/sync.py", line 41, in save_sync_library
    indent=4, separators=(',', ': ')))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2014' in position 86: ordinal not in range(128)

**Comment by jrnewell** [comment]
I think I fixed this issue in version ``2.4.1``, can you check?

**Comment by nholz** [comment]
Works!

**Comment by pihomeserver** [comment]
Not solved for me when i try to download a track (even after an upgrade) :
```
Error processing line 1 of /Library/Python/2.7/site-packages/easy-install.pth:

  Traceback (most recent call last):
    File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site.py", line 156, in addpackage
      if not dircase in known_paths and os.path.exists(dir):
    File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/genericpath.py", line 18, in exists
      os.stat(path)
  TypeError: must be encoded string without NULL bytes, not str

Remainder of file ignored
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/site-packages/spotify_ripper/ripper.py", line 270, in run
    self.prepare_rip(idx, track)
  File "/usr/local/lib/python2.7/site-packages/spotify_ripper/ripper.py", line 667, in prepare_rip
    print(Fore.CYAN + self.audio_file + Fore.RESET)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf4' in position 75: ordinal not in range(128)
```

**Comment by jrnewell** [comment]
I think I know what the issue is, but I am curious, which terminal are you using?

**Comment by pihomeserver** [comment]
I tried from bash it works. If i execute the command from nodeJS with exec function (i work on a GUI for spotify ripper) i got the error. It seems that the child_process uses /bin/sh on UNIX systems (even if i have a Mac)
If you need me to do some tests please ask me

**Comment by jrnewell** [comment]
OK I was able to replicate it using node.js spawn.  Can you try with ``2.5.1``?

**Comment by pihomeserver** [comment]
Perfect, works like a charm ! Thank you
